openapi: 3.0.1
info:
  title: LIPA API
  description: LIPA-Project API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /notes:
    get:
      summary: Find all notes
      operationId: findAllNotes
      responses:
        200:
          description: Find all notes available
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        201:
          description: The created note
          headers:
            Location:
              description: URL of the created note
              schema:
                type: string
                format: uri
  /notes/{id}:
    get:
      summary: Find a note with a specific id
      operationId: findNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: find a dedicated note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
    put:
      summary: Update a note
      operationId: updateNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        200:
          description: Object updated
        400:
          description: Bad request
        404:
          description: Object not found
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        text:
          type: string
        timestamp:
          type: string
          format: date-time
        category:
          type: string
      required:
        - id
        - title
        - timestamp
        - category
        - text